services:
  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  worker:
    build: .
    restart: always
    env_file: .env
    command: node queueWorker.js
    depends_on:
      - redis

  api:
    build: .
    restart: always
    env_file: .env
    ports:
      - "3800:3000"
    command: node api.js
    depends_on:
      - redis

volumes:
  redis_data:
